'use strict';
/* ===== FULL PANEL TRANSLATION ===== */
const PANEL_LANGS = {
  fr: {
    dir:'ltr',
    'nav-dash':'Dashboard','nav-clients':'Clients','nav-res':'Réservations','nav-vehicles':'Véhicules','nav-vidange':'Vidange',
    'cl-search-ph':'🔍 Rechercher un client...','cl-export':'📇 Exporter tous les contacts',
    'd-contract':'Contrat de location','btn-upload-contract':'Téléverser le contrat','btn-download':'Télécharger',
    'nav-stats':'Statistiques','settings':'Paramètres','logout':'Déconnexion',
    'lg-title':'Réservations','lg-connexion':'Connexion','lg-desc':'Accès réservé aux administrateurs',
    'lg-user':'Identifiant','lg-user-ph':'Votre identifiant','lg-pass':'Mot de passe','lg-submit':'Se connecter →',
    'lg-forgot':'Mot de passe oublié ?','lg-recovery':'🔑 Récupération','lg-answer':'Votre réponse','lg-verify':'Vérifier →',
    'lg-newuser':'Nouvel identifiant','lg-newpass':'Nouveau mot de passe','lg-reset':'Réinitialiser →','lg-back':'← Retour',
    'topbar-admin':'👤 Admin',
    'dash-recent':'Dernières réservations','dash-seeall':'Voir tout →','dash-pending':'En attente','dash-status':'Répartition des statuts',
    'res-search-ph':'🔍 Rechercher nom, voiture, ville, tél...','res-all':'Tous les statuts',
    'res-add':'➕ Ajouter une réservation','res-export':'⬇️ Export Excel','res-clear':'🗑️ Vider','res-empty':'Aucune réservation. Cliquez sur "➕ Ajouter une réservation".',
    'th-client':'Client','th-vehicle':'Véhicule','th-city':'Lieu','th-dates':'Dates','th-duration':'Durée',
    'th-total':'Total','th-payment':'Paiement','th-status':'Statut','th-actions':'Actions',
    'st-pending':'En attente','st-payment_pending':'Paiement en cours','st-confirmed':'Confirmé','st-completed':'Terminé','st-cancelled':'Annulé',
    'veh-add':'➕ Ajouter un véhicule','veh-empty':'Aucun véhicule. Cliquez sur "➕ Ajouter un véhicule".',
    'veh-available':'Disponible','veh-reserved':'Réservé','veh-maintenance':'Chez le mécanicien','veh-accident':'Accidenté',
    'vid-empty':'Aucun véhicule. Ajoutez des véhicules dans la section Véhicules.',
    'stat-status':'📊 Statuts','stat-topcars':'🚗 Top véhicules','stat-topcities':'📍 Top destinations','stat-revenue':'💰 Revenus par réservation',
    'set-lang-t':'🌐 Langue du panneau','set-lang':'Langue',
    'set-agency-t':"🏢 Informations de l'agence",'set-logo':"Logo de l'agence",'set-logo-remove':'🗑️ Retirer le logo',
    'set-name':"Nom de l'agence",'set-phone':'Téléphone / WhatsApp','set-email':'Email','set-address':'Adresse','set-save':'💾 Enregistrer',
    'set-creds-t':'🔐 Identifiants de connexion','set-newuser':'Nouvel identifiant','set-newpass':'Nouveau mot de passe',
    'set-newpass-ph':'Laisser vide pour ne pas changer','set-creds-save':'🔑 Mettre à jour les identifiants',
    'set-secq-t':'❓ Question de sécurité (récupération mot de passe)','set-question':'Question','set-answer':'Réponse','set-secq-save':'💾 Enregistrer la question',
    'set-danger-t':'⚠️ Zone de danger','set-danger-s':"Réinitialise toutes les données de l'application (réservations, voitures, offres, paramètres).",
    'set-danger-btn':'🗑️ Réinitialisation complète',
    'exp-title':'📊 Export Excel','exp-desc':'Choisissez la période à exporter.','exp-week':'📅 Cette semaine','exp-month':'🗓️ Ce mois (30 jours)',
    'exp-3m':'📆 3 derniers mois','exp-6m':'📆 6 derniers mois','exp-year':'📅 Cette année (12 mois)','exp-all':'🗂️ Toutes les données',
    'exp-download':'⬇️ Télécharger Excel','exp-cancel':'Annuler',
    'f-name':'Nom du client','f-phone':'Téléphone','f-email':'Email','f-email-opt':'Email (optionnel)',
    'f-vehicle':'Véhicule','f-vehicle-choose':'— Choisir —','f-city':'Lieu de livraison','f-start':'Date départ','f-end':'Date retour',
    'f-total':'Total (MAD)','f-paytype':'Statut paiement','f-paid-full':'✅ Payé complet','f-paid-deposit':'💳 Avance','f-paid-none':'⏳ Rien payé',
    'f-paid-amount':'Montant déjà payé / avance (MAD)','f-paid-amount2':'Déjà payé (MAD)',
    'f-caution-check':'Caution / Garantie prise','f-caution-amount':'Montant de la caution (MAD)',
    'btn-save':'💾 Enregistrer','btn-cancel':'Annuler','btn-update':'💾 Mettre à jour',
    'm-manual-title':'📞 Nouvelle réservation manuelle','m-edit-title':'✏️ Modifier la réservation',
    'avail-ok':'✅ Disponible pour ces dates','avail-no-accident':'❌ Indisponible — véhicule accidenté','avail-no-maint':'❌ Indisponible — chez le mécanicien',
    'avail-no-overlap':'❌ Indisponible — déjà réservé du','avail-to':'au',
    'd-client':'👤 Client','d-phone':'📞 Téléphone','d-email':'✉️ Email','d-vehicle':'🚗 Véhicule','d-place':'📍 Lieu',
    'd-start':'📅 Départ','d-end':'📅 Retour','d-duration':'⏱ Durée','d-price-day':'💵 Prix/jour','d-total':'💰 Total à payer',
    'd-payment':'💳 Paiement','d-paid':'✅ Déjà payé','d-due':'⏳ Reste','d-caution':'🔒 Caution','d-caution-none':'Non prise',
    'd-created':'🕐 Créé le','btn-edit-all':'✏️ Modifier toute la réservation','btn-confirm':'✅ Confirmer','btn-reject':'❌ Annuler',
    'btn-wa':'📲 WhatsApp','btn-delete':'🗑️ Supprimer','btn-close':'Fermer','btn-invoice':'🧾 Télécharger la facture',
    'm-vehicle-add':'Ajouter un véhicule','m-vehicle-edit':'Modifier un véhicule','m-vehicle-name':'Nom du véhicule','m-vehicle-plate':'Plaque',
    'm-vehicle-status':'Statut','m-vehicle-note':'Note (accident / mécanique)','m-vehicle-photos':'Photos du véhicule',
    'm-cal-title':'📅 Calendrier','m-block-title':'⛔ Réserver','m-block-client':'Client (optionnel)','m-block-save':'💾 Bloquer ces dates',
    'm-cal-avail':'🟢 Disponible','m-cal-reserved':'🔴 Réservé','m-cal-today':"🟡 Aujourd'hui",
    'vf-name':'Nom du véhicule','vf-plate':'Plaque','vf-brand':'Marque','vf-model':'Modèle','vf-year':'Année',
    'vf-color':'Couleur','vf-fuel':'Carburant','vf-gearbox':'Boîte','vf-price':'Prix/jour (MAD)','vf-mileage':'Kilométrage actuel',
    'vf-lastvidange':'Dernière vidange (km)','vf-interval':'Intervalle vidange (km)','vf-insurance':'Assurance — échéance','vf-visit':'Visite technique — échéance',
    'vid-due':'Vidange dépassée','vid-soon':'Vidange proche (≤1000km)','vid-ok':'OK','vid-overdue':'Vidange dépassée de','vid-remaining':'km restants',
    'vid-last':'Dernière vidange','vid-interval':'Intervalle','vid-next':'Prochaine vidange','btn-edit':'Modifier',
    titles:{dashboard:'📋 Dashboard',clients:'👥 Clients',reservations:'📋 Réservations',vehicles:'🚙 Véhicules',vidange:'🛢️ Vidange',stats:'📊 Statistiques',chats:'Conversations',settings:'⚙️ Paramètres'} },
  en: {
    dir:'ltr',
    'nav-dash':'Dashboard','nav-clients':'Clients','nav-res':'Reservations','nav-vehicles':'Vehicles','nav-vidange':'Oil change',
    'cl-search-ph':'🔍 Search a client...','cl-export':'📇 Export all contacts',
    'd-contract':'Rental contract','btn-upload-contract':'Upload contract','btn-download':'Download',
    'nav-stats':'Statistics','settings':'Settings','logout':'Log out',
    'lg-title':'Reservations','lg-connexion':'Login','lg-desc':'Restricted to administrators',
    'lg-user':'Username','lg-user-ph':'Your username','lg-pass':'Password','lg-submit':'Sign in →',
    'lg-forgot':'Forgot password?','lg-recovery':'🔑 Recovery','lg-answer':'Your answer','lg-verify':'Verify →',
    'lg-newuser':'New username','lg-newpass':'New password','lg-reset':'Reset →','lg-back':'← Back',
    'topbar-admin':'👤 Admin',
    'dash-recent':'Latest reservations','dash-seeall':'See all →','dash-pending':'Pending','dash-status':'Status breakdown',
    'res-search-ph':'🔍 Search name, car, city, phone...','res-all':'All statuses',
    'res-add':'➕ Add a reservation','res-export':'⬇️ Export Excel','res-clear':'🗑️ Clear','res-empty':'No reservations. Click "➕ Add a reservation".',
    'th-client':'Client','th-vehicle':'Vehicle','th-city':'Location','th-dates':'Dates','th-duration':'Duration',
    'th-total':'Total','th-payment':'Payment','th-status':'Status','th-actions':'Actions',
    'st-pending':'Pending','st-payment_pending':'Payment in progress','st-confirmed':'Confirmed','st-completed':'Completed','st-cancelled':'Cancelled',
    'veh-add':'➕ Add a vehicle','veh-empty':'No vehicles. Click "➕ Add a vehicle".',
    'veh-available':'Available','veh-reserved':'Reserved','veh-maintenance':'At the mechanic','veh-accident':'In an accident',
    'vid-empty':'No vehicles. Add vehicles in the Vehicles section.',
    'stat-status':'📊 Statuses','stat-topcars':'🚗 Top vehicles','stat-topcities':'📍 Top destinations','stat-revenue':'💰 Revenue per reservation',
    'set-lang-t':'🌐 Panel language','set-lang':'Language',
    'set-agency-t':'🏢 Agency information','set-logo':'Agency logo','set-logo-remove':'🗑️ Remove logo',
    'set-name':'Agency name','set-phone':'Phone / WhatsApp','set-email':'Email','set-address':'Address','set-save':'💾 Save',
    'set-creds-t':'🔐 Login credentials','set-newuser':'New username','set-newpass':'New password',
    'set-newpass-ph':'Leave empty to keep current','set-creds-save':'🔑 Update credentials',
    'set-secq-t':'❓ Security question (password recovery)','set-question':'Question','set-answer':'Answer','set-secq-save':'💾 Save question',
    'set-danger-t':'⚠️ Danger zone','set-danger-s':'Resets all app data (reservations, cars, offers, settings).',
    'set-danger-btn':'🗑️ Full reset',
    'exp-title':'📊 Excel export','exp-desc':'Choose the period to export.','exp-week':'📅 This week','exp-month':'🗓️ This month (30 days)',
    'exp-3m':'📆 Last 3 months','exp-6m':'📆 Last 6 months','exp-year':'📅 This year (12 months)','exp-all':'🗂️ All data',
    'exp-download':'⬇️ Download Excel','exp-cancel':'Cancel',
    'f-name':'Client name','f-phone':'Phone','f-email':'Email','f-email-opt':'Email (optional)',
    'f-vehicle':'Vehicle','f-vehicle-choose':'— Choose —','f-city':'Delivery location','f-start':'Start date','f-end':'Return date',
    'f-total':'Total (MAD)','f-paytype':'Payment status','f-paid-full':'✅ Fully paid','f-paid-deposit':'💳 Deposit','f-paid-none':'⏳ Nothing paid',
    'f-paid-amount':'Amount already paid / deposit (MAD)','f-paid-amount2':'Already paid (MAD)',
    'f-caution-check':'Security deposit taken','f-caution-amount':'Deposit amount (MAD)',
    'btn-save':'💾 Save','btn-cancel':'Cancel','btn-update':'💾 Update',
    'm-manual-title':'📞 New manual reservation','m-edit-title':'✏️ Edit reservation',
    'avail-ok':'✅ Available for these dates','avail-no-accident':'❌ Unavailable — vehicle in an accident','avail-no-maint':'❌ Unavailable — at the mechanic',
    'avail-no-overlap':'❌ Unavailable — already booked from','avail-to':'to',
    'd-client':'👤 Client','d-phone':'📞 Phone','d-email':'✉️ Email','d-vehicle':'🚗 Vehicle','d-place':'📍 Location',
    'd-start':'📅 Departure','d-end':'📅 Return','d-duration':'⏱ Duration','d-price-day':'💵 Price/day','d-total':'💰 Total due',
    'd-payment':'💳 Payment','d-paid':'✅ Already paid','d-due':'⏳ Remaining','d-caution':'🔒 Deposit','d-caution-none':'Not taken',
    'd-created':'🕐 Created on','btn-edit-all':'✏️ Edit whole reservation','btn-confirm':'✅ Confirm','btn-reject':'❌ Cancel',
    'btn-wa':'📲 WhatsApp','btn-delete':'🗑️ Delete','btn-close':'Close','btn-invoice':'🧾 Download invoice',
    'm-vehicle-add':'Add a vehicle','m-vehicle-edit':'Edit vehicle','m-vehicle-name':'Vehicle name','m-vehicle-plate':'Plate',
    'm-vehicle-status':'Status','m-vehicle-note':'Note (accident / mechanic)','m-vehicle-photos':'Vehicle photos',
    'm-cal-title':'📅 Calendar','m-block-title':'⛔ Reserve','m-block-client':'Client (optional)','m-block-save':'💾 Block these dates',
    'm-cal-avail':'🟢 Available','m-cal-reserved':'🔴 Reserved','m-cal-today':'🟡 Today',
    'vf-name':'Vehicle name','vf-plate':'Plate','vf-brand':'Brand','vf-model':'Model','vf-year':'Year',
    'vf-color':'Color','vf-fuel':'Fuel','vf-gearbox':'Gearbox','vf-price':'Price/day (MAD)','vf-mileage':'Current mileage',
    'vf-lastvidange':'Last oil change (km)','vf-interval':'Oil change interval (km)','vf-insurance':'Insurance — due date','vf-visit':'Technical inspection — due date',
    'vid-due':'Oil change overdue','vid-soon':'Oil change soon (≤1000km)','vid-ok':'OK','vid-overdue':'Overdue by','vid-remaining':'km remaining',
    'vid-last':'Last oil change','vid-interval':'Interval','vid-next':'Next oil change','btn-edit':'Edit',
    titles:{dashboard:'📋 Dashboard',clients:'👥 Clients',reservations:'📋 Reservations',vehicles:'🚙 Vehicles',vidange:'🛢️ Oil change',stats:'📊 Statistics',chats:'Conversations',settings:'⚙️ Settings'} },
  ar: {
    dir:'rtl',
    'nav-dash':'لوحة التحكم','nav-clients':'العملاء','nav-res':'الحجوزات','nav-vehicles':'السيارات','nav-vidange':'الفيدانج',
    'cl-search-ph':'🔍 ابحث عن عميل...','cl-export':'📇 تصدير كل جهات الاتصال',
    'd-contract':'عقد الكراء','btn-upload-contract':'رفع العقد','btn-download':'تحميل',
    'nav-stats':'الإحصائيات','settings':'الإعدادات','logout':'تسجيل الخروج',
    'lg-title':'الحجوزات','lg-connexion':'تسجيل الدخول','lg-desc':'الدخول مخصص للمسؤولين فقط',
    'lg-user':'اسم المستخدم','lg-user-ph':'اسم المستخدم ديالك','lg-pass':'كلمة السر','lg-submit':'← دخول',
    'lg-forgot':'نسيتي كلمة السر؟','lg-recovery':'🔑 استرجاع','lg-answer':'الجواب ديالك','lg-verify':'← تحقق',
    'lg-newuser':'اسم مستخدم جديد','lg-newpass':'كلمة سر جديدة','lg-reset':'← إعادة تعيين','lg-back':'رجوع →',
    'topbar-admin':'👤 المسؤول',
    'dash-recent':'آخر الحجوزات','dash-seeall':'← شوف الكل','dash-pending':'فالانتظار','dash-status':'توزيع الحالات',
    'res-search-ph':'🔍 بحث بالاسم، السيارة، المدينة، الهاتف...','res-all':'جميع الحالات',
    'res-add':'➕ إضافة حجز','res-export':'⬇️ تصدير Excel','res-clear':'🗑️ مسح','res-empty':'لا توجد حجوزات. اضغط على "➕ إضافة حجز".',
    'th-client':'الكليان','th-vehicle':'السيارة','th-city':'المكان','th-dates':'التواريخ','th-duration':'المدة',
    'th-total':'الإجمالي','th-payment':'الدفع','th-status':'الحالة','th-actions':'إجراءات',
    'st-pending':'فالانتظار','st-payment_pending':'الدفع جاري','st-confirmed':'مؤكد','st-completed':'منتهي','st-cancelled':'ملغى',
    'veh-add':'➕ إضافة سيارة','veh-empty':'لا توجد سيارات. اضغط على "➕ إضافة سيارة".',
    'veh-available':'متاحة','veh-reserved':'محجوزة','veh-maintenance':'عند المكانيك','veh-accident':'حادثة',
    'vid-empty':'لا توجد سيارات. زيد سيارات فقسم السيارات.',
    'stat-status':'📊 الحالات','stat-topcars':'🚗 أفضل السيارات','stat-topcities':'📍 أفضل الوجهات','stat-revenue':'💰 الإيرادات حسب الحجز',
    'set-lang-t':'🌐 لغة لوحة التحكم','set-lang':'اللغة',
    'set-agency-t':'🏢 معلومات الوكالة','set-logo':'شعار الوكالة','set-logo-remove':'🗑️ حذف الشعار',
    'set-name':'اسم الوكالة','set-phone':'الهاتف / واتساب','set-email':'البريد الإلكتروني','set-address':'العنوان','set-save':'💾 حفظ',
    'set-creds-t':'🔐 معلومات تسجيل الدخول','set-newuser':'اسم مستخدم جديد','set-newpass':'كلمة سر جديدة',
    'set-newpass-ph':'خليه خاوي إلا ماباغيش تبدلو','set-creds-save':'🔑 تحديث المعلومات',
    'set-secq-t':'❓ سؤال الأمان (استرجاع كلمة السر)','set-question':'السؤال','set-answer':'الجواب','set-secq-save':'💾 حفظ السؤال',
    'set-danger-t':'⚠️ منطقة الخطر','set-danger-s':'كيصيفط جميع بيانات التطبيق (الحجوزات، السيارات، العروض، الإعدادات).',
    'set-danger-btn':'🗑️ إعادة تعيين كاملة',
    'exp-title':'📊 تصدير Excel','exp-desc':'اختر الفترة للتصدير.','exp-week':'📅 هاد الأسبوع','exp-month':'🗓️ هاد الشهر (30 يوم)',
    'exp-3m':'📆 آخر 3 أشهر','exp-6m':'📆 آخر 6 أشهر','exp-year':'📅 هاد السنة (12 شهر)','exp-all':'🗂️ جميع البيانات',
    'exp-download':'⬇️ تحميل Excel','exp-cancel':'إلغاء',
    'f-name':'اسم الكليان','f-phone':'الهاتف','f-email':'البريد الإلكتروني','f-email-opt':'البريد الإلكتروني (اختياري)',
    'f-vehicle':'السيارة','f-vehicle-choose':'— اختر —','f-city':'مكان التوصيل','f-start':'تاريخ الذهاب','f-end':'تاريخ الرجوع',
    'f-total':'الإجمالي (MAD)','f-paytype':'حالة الدفع','f-paid-full':'✅ مدفوع بالكامل','f-paid-deposit':'💳 تقدمة','f-paid-none':'⏳ ماشي مدفوع',
    'f-paid-amount':'المبلغ المدفوع / التقدمة (MAD)','f-paid-amount2':'المدفوع (MAD)',
    'f-caution-check':'الضمان/الكوسيون مأخوذ','f-caution-amount':'مبلغ الضمان (MAD)',
    'btn-save':'💾 حفظ','btn-cancel':'إلغاء','btn-update':'💾 تحديث',
    'm-manual-title':'📞 حجز يدوي جديد','m-edit-title':'✏️ تعديل الحجز',
    'avail-ok':'✅ متاحة فهاد التواريخ','avail-no-accident':'❌ غير متاحة — السيارة حادثة','avail-no-maint':'❌ غير متاحة — عند المكانيك',
    'avail-no-overlap':'❌ غير متاحة — محجوزة من','avail-to':'إلى',
    'd-client':'👤 الكليان','d-phone':'📞 الهاتف','d-email':'✉️ البريد الإلكتروني','d-vehicle':'🚗 السيارة','d-place':'📍 المكان',
    'd-start':'📅 الذهاب','d-end':'📅 الرجوع','d-duration':'⏱ المدة','d-price-day':'💵 السعر/اليوم','d-total':'💰 الإجمالي للدفع',
    'd-payment':'💳 الدفع','d-paid':'✅ المدفوع','d-due':'⏳ الباقي','d-caution':'🔒 الضمان','d-caution-none':'ماخدمتش',
    'd-created':'🕐 تسجل فـ','btn-edit-all':'✏️ تعديل الحجز كامل','btn-confirm':'✅ تأكيد','btn-reject':'❌ إلغاء',
    'btn-wa':'📲 واتساب','btn-delete':'🗑️ حذف','btn-close':'إغلاق','btn-invoice':'🧾 تحميل الفاكتور',
    'm-vehicle-add':'إضافة سيارة','m-vehicle-edit':'تعديل سيارة','m-vehicle-name':'اسم السيارة','m-vehicle-plate':'الماتريكول',
    'm-vehicle-status':'الحالة','m-vehicle-note':'ملاحظة (أكسيدون / مكانيك)','m-vehicle-photos':'صور السيارة',
    'm-cal-title':'📅 الكلندري','m-block-title':'⛔ حجز','m-block-client':'الكليان (اختياري)','m-block-save':'💾 حجز هاد التواريخ',
    'm-cal-avail':'🟢 متاحة','m-cal-reserved':'🔴 محجوزة','m-cal-today':'🟡 اليوم',
    'vf-name':'اسم السيارة','vf-plate':'الماتريكول','vf-brand':'الماركة','vf-model':'الموديل','vf-year':'السنة',
    'vf-color':'الكولور','vf-fuel':'الكاربوران','vf-gearbox':'البواط','vf-price':'السعر/اليوم (MAD)','vf-mileage':'الكيلومتراج الحالي',
    'vf-lastvidange':'آخر فيدانج (km)','vf-interval':'إنترفال الفيدانج (km)','vf-insurance':'التأمين — تاريخ الانتهاء','vf-visit':'الزيارة التقنية — تاريخ الانتهاء',
    'vid-due':'الفيدانج فاتت','vid-soon':'الفيدانج قريبة (≤1000km)','vid-ok':'مزيان','vid-overdue':'فاتت بـ','vid-remaining':'كم باقي',
    'vid-last':'آخر فيدانج','vid-interval':'الإنترفال','vid-next':'الفيدانج الجاية','btn-edit':'تعديل',
    titles:{dashboard:'📋 لوحة التحكم',clients:'👥 العملاء',reservations:'📋 الحجوزات',vehicles:'🚙 السيارات',vidange:'🛢️ الفيدانج',stats:'📊 الإحصائيات',chats:'المحادثات',settings:'⚙️ الإعدادات'} },
  es: {
    dir:'ltr',
    'nav-dash':'Tablero','nav-clients':'Clientes','nav-res':'Reservas','nav-vehicles':'Vehículos','nav-vidange':'Cambio de aceite',
    'cl-search-ph':'🔍 Buscar un cliente...','cl-export':'📇 Exportar todos los contactos',
    'd-contract':'Contrato de alquiler','btn-upload-contract':'Subir contrato','btn-download':'Descargar',
    'nav-stats':'Estadísticas','settings':'Ajustes','logout':'Cerrar sesión',
    'lg-title':'Reservas','lg-connexion':'Iniciar sesión','lg-desc':'Acceso reservado a administradores',
    'lg-user':'Usuario','lg-user-ph':'Tu usuario','lg-pass':'Contraseña','lg-submit':'Entrar →',
    'lg-forgot':'¿Olvidaste la contraseña?','lg-recovery':'🔑 Recuperación','lg-answer':'Tu respuesta','lg-verify':'Verificar →',
    'lg-newuser':'Nuevo usuario','lg-newpass':'Nueva contraseña','lg-reset':'Restablecer →','lg-back':'← Volver',
    'topbar-admin':'👤 Admin',
    'dash-recent':'Últimas reservas','dash-seeall':'Ver todo →','dash-pending':'Pendiente','dash-status':'Distribución de estados',
    'res-search-ph':'🔍 Buscar nombre, coche, ciudad, tel...','res-all':'Todos los estados',
    'res-add':'➕ Añadir una reserva','res-export':'⬇️ Exportar Excel','res-clear':'🗑️ Vaciar','res-empty':'No hay reservas. Haz clic en "➕ Añadir una reserva".',
    'th-client':'Cliente','th-vehicle':'Vehículo','th-city':'Lugar','th-dates':'Fechas','th-duration':'Duración',
    'th-total':'Total','th-payment':'Pago','th-status':'Estado','th-actions':'Acciones',
    'st-pending':'Pendiente','st-payment_pending':'Pago en curso','st-confirmed':'Confirmado','st-completed':'Finalizado','st-cancelled':'Cancelado',
    'veh-add':'➕ Añadir un vehículo','veh-empty':'No hay vehículos. Haz clic en "➕ Añadir un vehículo".',
    'veh-available':'Disponible','veh-reserved':'Reservado','veh-maintenance':'En el mecánico','veh-accident':'Accidentado',
    'vid-empty':'No hay vehículos. Añade vehículos en la sección Vehículos.',
    'stat-status':'📊 Estados','stat-topcars':'🚗 Mejores vehículos','stat-topcities':'📍 Mejores destinos','stat-revenue':'💰 Ingresos por reserva',
    'set-lang-t':'🌐 Idioma del panel','set-lang':'Idioma',
    'set-agency-t':'🏢 Información de la agencia','set-logo':'Logo de la agencia','set-logo-remove':'🗑️ Quitar el logo',
    'set-name':'Nombre de la agencia','set-phone':'Teléfono / WhatsApp','set-email':'Email','set-address':'Dirección','set-save':'💾 Guardar',
    'set-creds-t':'🔐 Credenciales de acceso','set-newuser':'Nuevo usuario','set-newpass':'Nueva contraseña',
    'set-newpass-ph':'Dejar vacío para no cambiar','set-creds-save':'🔑 Actualizar credenciales',
    'set-secq-t':'❓ Pregunta de seguridad (recuperación de contraseña)','set-question':'Pregunta','set-answer':'Respuesta','set-secq-save':'💾 Guardar la pregunta',
    'set-danger-t':'⚠️ Zona de peligro','set-danger-s':'Restablece todos los datos de la aplicación (reservas, coches, ofertas, ajustes).',
    'set-danger-btn':'🗑️ Restablecimiento completo',
    'exp-title':'📊 Exportar Excel','exp-desc':'Elige el periodo a exportar.','exp-week':'📅 Esta semana','exp-month':'🗓️ Este mes (30 días)',
    'exp-3m':'📆 Últimos 3 meses','exp-6m':'📆 Últimos 6 meses','exp-year':'📅 Este año (12 meses)','exp-all':'🗂️ Todos los datos',
    'exp-download':'⬇️ Descargar Excel','exp-cancel':'Cancelar',
    'f-name':'Nombre del cliente','f-phone':'Teléfono','f-email':'Email','f-email-opt':'Email (opcional)',
    'f-vehicle':'Vehículo','f-vehicle-choose':'— Elegir —','f-city':'Lugar de entrega','f-start':'Fecha de salida','f-end':'Fecha de regreso',
    'f-total':'Total (MAD)','f-paytype':'Estado del pago','f-paid-full':'✅ Pagado completo','f-paid-deposit':'💳 Anticipo','f-paid-none':'⏳ Nada pagado',
    'f-paid-amount':'Importe ya pagado / anticipo (MAD)','f-paid-amount2':'Ya pagado (MAD)',
    'f-caution-check':'Fianza / Garantía tomada','f-caution-amount':'Importe de la fianza (MAD)',
    'btn-save':'💾 Guardar','btn-cancel':'Cancelar','btn-update':'💾 Actualizar',
    'm-manual-title':'📞 Nueva reserva manual','m-edit-title':'✏️ Editar la reserva',
    'avail-ok':'✅ Disponible para estas fechas','avail-no-accident':'❌ No disponible — vehículo accidentado','avail-no-maint':'❌ No disponible — en el mecánico',
    'avail-no-overlap':'❌ No disponible — ya reservado del','avail-to':'al',
    'd-client':'👤 Cliente','d-phone':'📞 Teléfono','d-email':'✉️ Email','d-vehicle':'🚗 Vehículo','d-place':'📍 Lugar',
    'd-start':'📅 Salida','d-end':'📅 Regreso','d-duration':'⏱ Duración','d-price-day':'💵 Precio/día','d-total':'💰 Total a pagar',
    'd-payment':'💳 Pago','d-paid':'✅ Ya pagado','d-due':'⏳ Restante','d-caution':'🔒 Fianza','d-caution-none':'No tomada',
    'd-created':'🕐 Creado el','btn-edit-all':'✏️ Editar toda la reserva','btn-confirm':'✅ Confirmar','btn-reject':'❌ Cancelar',
    'btn-wa':'📲 WhatsApp','btn-delete':'🗑️ Eliminar','btn-close':'Cerrar','btn-invoice':'🧾 Descargar la factura',
    'm-vehicle-add':'Añadir un vehículo','m-vehicle-edit':'Editar vehículo','m-vehicle-name':'Nombre del vehículo','m-vehicle-plate':'Matrícula',
    'm-vehicle-status':'Estado','m-vehicle-note':'Nota (accidente / mecánica)','m-vehicle-photos':'Fotos del vehículo',
    'm-cal-title':'📅 Calendario','m-block-title':'⛔ Reservar','m-block-client':'Cliente (opcional)','m-block-save':'💾 Bloquear estas fechas',
    'm-cal-avail':'🟢 Disponible','m-cal-reserved':'🔴 Reservado','m-cal-today':'🟡 Hoy',
    'vf-name':'Nombre del vehículo','vf-plate':'Matrícula','vf-brand':'Marca','vf-model':'Modelo','vf-year':'Año',
    'vf-color':'Color','vf-fuel':'Combustible','vf-gearbox':'Caja de cambios','vf-price':'Precio/día (MAD)','vf-mileage':'Kilometraje actual',
    'vf-lastvidange':'Último cambio de aceite (km)','vf-interval':'Intervalo de cambio (km)','vf-insurance':'Seguro — vencimiento','vf-visit':'Inspección técnica — vencimiento',
    'vid-due':'Cambio de aceite vencido','vid-soon':'Cambio de aceite próximo (≤1000km)','vid-ok':'OK','vid-overdue':'Vencido por','vid-remaining':'km restantes',
    'vid-last':'Último cambio','vid-interval':'Intervalo','vid-next':'Próximo cambio','btn-edit':'Editar',
    titles:{dashboard:'📋 Tablero',clients:'👥 Clientes',reservations:'📋 Reservas',vehicles:'🚙 Vehículos',vidange:'🛢️ Cambio de aceite',stats:'📊 Estadísticas',chats:'Conversaciones',settings:'⚙️ Ajustes'} },
};

/* ===== Supplementary keys (dashboard JS, échéances, business panel, landing) ===== */
const _MORE = {
  fr: {
    'k-due':'Restant à percevoir (MAD)','k-due-warn':'Avances en attente','k-paid-all':'Tout payé ✓',
    'k-total':'Total réservations','k-pending-sfx':'en attente','k-alldone':'Tout traité ✓',
    'k-ca':"Chiffre d'affaires (MAD)",'k-ca-sub':'Réservations terminées uniquement',
    'k-waiting':'En attente','k-pay-progress':'paiement en cours','k-action':'Action requise','k-none-waiting':'Aucune en attente',
    'k-confirmed':'Confirmées','k-cancelled-sfx':'annulée(s)','k-nocancel':'0 annulation',
    'empty-res':'Aucune réservation','empty-pending':'Aucune en attente ✓','mycompte':'Mon compte',
    'ech-title':'🔔 Échéances proches — Assurance, Visite technique & Vidange','ech-engine':'entretien moteur','ech-due':'échéance',
    'lbl-vid-over':'vidange dépassée de','lbl-vid-in':'vidange dans','lbl-over-since':'dépassée depuis','lbl-expire-today':"expire aujourd'hui",'lbl-in':'dans',
    'biz-loading':'Chargement de votre espace…','biz-multi':'Multi-Agences','biz-sub':'Plan Business — chaque agence a son propre système isolé.',
    'biz-global':'🌐 Vue globale','biz-agencies':'🏢 Mes agences','biz-eyebrow':'Tableau de bord consolidé','biz-h2':"Toutes vos agences en un coup d'œil",
    'biz-detail':'Détail par agence','biz-gestion':'Gestion','biz-new':'➕ Nouvelle agence',
    'biz-k-ag':'Agences','biz-k-veh':'Véhicules (total)','biz-k-res':'Réservations (total)','biz-k-cl':'Clients (total)','biz-k-ca':"Chiffre d'affaires (MAD)",
    'biz-th-ag':'Agence','biz-th-veh':'Véhicules','biz-th-res':'Réservations','biz-th-cl':'Clients','biz-th-ca':'CA (MAD)',
    'biz-open':'Ouvrir →','biz-opensys':'Ouvrir le système →','biz-created':'Créée le','biz-veh':'Véhicules','biz-res-s':'Réserv.','biz-ca-s':'CA MAD',
    'biz-empty':'Aucune agence. Créez-en une dans « Mes agences ».','biz-newcard':'Nouvelle agence','biz-logout':'🚪 Déconnexion',
    'lp-login':'Se connecter','lp-signup':"S'inscrire",'lp-badge':'Nouvelle génération de gestion automobile',
    'lp-hero1':'Votre agence de location','lp-hero2':'entre dans','lp-hero3':'une autre dimension',
    'lp-lead':"Réservations, parc auto, échéances d'assurance, statistiques et rappels WhatsApp — toute votre agence pilotée depuis un seul cockpit intelligent, accessible partout, à chaque instant.",
    'lp-cta1':'Commencer gratuitement →','lp-cta2':'Découvrir les offres',
  },
  en: {
    'k-due':'Outstanding to collect (MAD)','k-due-warn':'Deposits pending','k-paid-all':'All paid ✓',
    'k-total':'Total reservations','k-pending-sfx':'pending','k-alldone':'All handled ✓',
    'k-ca':'Revenue (MAD)','k-ca-sub':'Completed reservations only',
    'k-waiting':'Pending','k-pay-progress':'payment in progress','k-action':'Action required','k-none-waiting':'None pending',
    'k-confirmed':'Confirmed','k-cancelled-sfx':'cancelled','k-nocancel':'0 cancellation',
    'empty-res':'No reservations','empty-pending':'None pending ✓','mycompte':'My account',
    'ech-title':'🔔 Upcoming due dates — Insurance, Technical inspection & Oil change','ech-engine':'engine service','ech-due':'due',
    'lbl-vid-over':'oil change overdue by','lbl-vid-in':'oil change in','lbl-over-since':'overdue by','lbl-expire-today':'expires today','lbl-in':'in',
    'biz-loading':'Loading your space…','biz-multi':'Multi-Agencies','biz-sub':'Business plan — each agency has its own isolated system.',
    'biz-global':'🌐 Global view','biz-agencies':'🏢 My agencies','biz-eyebrow':'Consolidated dashboard','biz-h2':'All your agencies at a glance',
    'biz-detail':'Breakdown by agency','biz-gestion':'Management','biz-new':'➕ New agency',
    'biz-k-ag':'Agencies','biz-k-veh':'Vehicles (total)','biz-k-res':'Reservations (total)','biz-k-cl':'Clients (total)','biz-k-ca':'Revenue (MAD)',
    'biz-th-ag':'Agency','biz-th-veh':'Vehicles','biz-th-res':'Reservations','biz-th-cl':'Clients','biz-th-ca':'Rev. (MAD)',
    'biz-open':'Open →','biz-opensys':'Open the system →','biz-created':'Created on','biz-veh':'Vehicles','biz-res-s':'Resv.','biz-ca-s':'Rev. MAD',
    'biz-empty':'No agency. Create one in “My agencies”.','biz-newcard':'New agency','biz-logout':'🚪 Log out',
    'lp-login':'Log in','lp-signup':'Sign up','lp-badge':'Next-generation car fleet management',
    'lp-hero1':'Your rental agency','lp-hero2':'enters','lp-hero3':'another dimension',
    'lp-lead':'Reservations, fleet, insurance due dates, statistics and WhatsApp reminders — your whole agency run from a single smart cockpit, accessible everywhere, anytime.',
    'lp-cta1':'Start for free →','lp-cta2':'Discover the plans',
  },
  ar: {
    'k-due':'الباقي للتحصيل (MAD)','k-due-warn':'تسبيقات فالانتظار','k-paid-all':'خالص بالكامل ✓',
    'k-total':'إجمالي الحجوزات','k-pending-sfx':'فالانتظار','k-alldone':'كلشي متعالج ✓',
    'k-ca':'رقم المعاملات (MAD)','k-ca-sub':'الحجوزات المنتهية فقط',
    'k-waiting':'فالانتظار','k-pay-progress':'الدفع جاري','k-action':'إجراء مطلوب','k-none-waiting':'لا شيء فالانتظار',
    'k-confirmed':'مؤكدة','k-cancelled-sfx':'ملغاة','k-nocancel':'0 إلغاء',
    'empty-res':'لا توجد حجوزات','empty-pending':'لا شيء فالانتظار ✓','mycompte':'حسابي',
    'ech-title':'🔔 استحقاقات قريبة — التأمين، الزيارة التقنية والفيدانج','ech-engine':'صيانة المحرك','ech-due':'استحقاق',
    'lbl-vid-over':'الفيدانج فاتت بـ','lbl-vid-in':'الفيدانج فـ','lbl-over-since':'فاتت بـ','lbl-expire-today':'كتسالي اليوم','lbl-in':'فـ',
    'biz-loading':'كيتحمّل الفضاء ديالك…','biz-multi':'متعدد الوكالات','biz-sub':'خطة Business — كل وكالة عندها نظام مستقل خاص بها.',
    'biz-global':'🌐 نظرة عامة','biz-agencies':'🏢 وكالاتي','biz-eyebrow':'لوحة تحكم موحّدة','biz-h2':'جميع وكالاتك بنظرة واحدة',
    'biz-detail':'التفصيل حسب الوكالة','biz-gestion':'التدبير','biz-new':'➕ وكالة جديدة',
    'biz-k-ag':'الوكالات','biz-k-veh':'السيارات (المجموع)','biz-k-res':'الحجوزات (المجموع)','biz-k-cl':'العملاء (المجموع)','biz-k-ca':'رقم المعاملات (MAD)',
    'biz-th-ag':'الوكالة','biz-th-veh':'السيارات','biz-th-res':'الحجوزات','biz-th-cl':'العملاء','biz-th-ca':'المعاملات (MAD)',
    'biz-open':'فتح →','biz-opensys':'فتح النظام →','biz-created':'أُنشئت فـ','biz-veh':'السيارات','biz-res-s':'حجوزات','biz-ca-s':'المعاملات MAD',
    'biz-empty':'لا توجد وكالة. أنشئ وحدة فـ«وكالاتي».','biz-newcard':'وكالة جديدة','biz-logout':'🚪 تسجيل الخروج',
    'lp-login':'تسجيل الدخول','lp-signup':'إنشاء حساب','lp-badge':'الجيل الجديد لتدبير السيارات',
    'lp-hero1':'وكالة الكراء ديالك','lp-hero2':'كتدخل لـ','lp-hero3':'بُعد آخر',
    'lp-lead':'الحجوزات، حظيرة السيارات، استحقاقات التأمين، الإحصائيات وتذكيرات واتساب — وكالتك كاملة مُدارة من لوحة ذكية واحدة، فأي مكان وفأي وقت.',
    'lp-cta1':'ابدأ مجاناً →','lp-cta2':'اكتشف العروض',
  },
  es: {
    'k-due':'Pendiente de cobro (MAD)','k-due-warn':'Anticipos pendientes','k-paid-all':'Todo pagado ✓',
    'k-total':'Total de reservas','k-pending-sfx':'pendientes','k-alldone':'Todo gestionado ✓',
    'k-ca':'Facturación (MAD)','k-ca-sub':'Solo reservas finalizadas',
    'k-waiting':'Pendiente','k-pay-progress':'pago en curso','k-action':'Acción requerida','k-none-waiting':'Nada pendiente',
    'k-confirmed':'Confirmadas','k-cancelled-sfx':'cancelada(s)','k-nocancel':'0 cancelación',
    'empty-res':'No hay reservas','empty-pending':'Nada pendiente ✓','mycompte':'Mi cuenta',
    'ech-title':'🔔 Vencimientos próximos — Seguro, Inspección técnica y Cambio de aceite','ech-engine':'mantenimiento del motor','ech-due':'vencimiento',
    'lbl-vid-over':'cambio de aceite vencido por','lbl-vid-in':'cambio de aceite en','lbl-over-since':'vencido por','lbl-expire-today':'vence hoy','lbl-in':'en',
    'biz-loading':'Cargando tu espacio…','biz-multi':'Multi-Agencias','biz-sub':'Plan Business — cada agencia tiene su propio sistema aislado.',
    'biz-global':'🌐 Vista global','biz-agencies':'🏢 Mis agencias','biz-eyebrow':'Panel consolidado','biz-h2':'Todas tus agencias de un vistazo',
    'biz-detail':'Detalle por agencia','biz-gestion':'Gestión','biz-new':'➕ Nueva agencia',
    'biz-k-ag':'Agencias','biz-k-veh':'Vehículos (total)','biz-k-res':'Reservas (total)','biz-k-cl':'Clientes (total)','biz-k-ca':'Facturación (MAD)',
    'biz-th-ag':'Agencia','biz-th-veh':'Vehículos','biz-th-res':'Reservas','biz-th-cl':'Clientes','biz-th-ca':'Fact. (MAD)',
    'biz-open':'Abrir →','biz-opensys':'Abrir el sistema →','biz-created':'Creada el','biz-veh':'Vehículos','biz-res-s':'Reserv.','biz-ca-s':'Fact. MAD',
    'biz-empty':'No hay agencia. Crea una en «Mis agencias».','biz-newcard':'Nueva agencia','biz-logout':'🚪 Cerrar sesión',
    'lp-login':'Iniciar sesión','lp-signup':'Registrarse','lp-badge':'Gestión de flota de nueva generación',
    'lp-hero1':'Tu agencia de alquiler','lp-hero2':'entra en','lp-hero3':'otra dimensión',
    'lp-lead':'Reservas, flota, vencimientos de seguro, estadísticas y recordatorios de WhatsApp — toda tu agencia gestionada desde un único panel inteligente, accesible en todas partes, en todo momento.',
    'lp-cta1':'Empezar gratis →','lp-cta2':'Descubrir los planes',
  },
};
for (const c in _MORE) Object.assign(PANEL_LANGS[c], _MORE[c]);

function curLang() { return localStorage.getItem('md_panel_lang') || 'fr'; }
function T(key) { const L = PANEL_LANGS[curLang()] || PANEL_LANGS.fr; return L[key] != null ? L[key] : (PANEL_LANGS.fr[key] || key); }

function applyPanelLang(code) {
  const L = PANEL_LANGS[code] || PANEL_LANGS.fr;
  localStorage.setItem('md_panel_lang', code);
  document.documentElement.lang = code;
  document.documentElement.dir = L.dir;
  document.querySelectorAll('[data-pt]').forEach(el => {
    const v = L[el.dataset.pt];
    if (v) el.textContent = v;
  });
  document.querySelectorAll('[data-pt-ph]').forEach(el => {
    const v = L[el.dataset.ptPh];
    if (v) el.placeholder = v;
  });
  ['panelLangSel', 'topLangSel'].forEach(id => { const s = document.getElementById(id); if (s) s.value = code; });
  const pageTitle = document.getElementById('pageTitle');
  if (pageTitle && window.currentAdminTab) pageTitle.textContent = L.titles[window.currentAdminTab] || pageTitle.textContent;
  if (window.currentAdminTab && typeof showTab === 'function' && document.getElementById('app')?.style.display !== 'none') {
    const activeLink = document.querySelector('.sb-link.active');
    if (activeLink) showTab(window.currentAdminTab, activeLink);
  }
}

document.addEventListener('DOMContentLoaded', () => {
  applyPanelLang(localStorage.getItem('md_panel_lang') || 'fr');
});
