'use strict';
/* ===== FULL PANEL TRANSLATION ===== */
const PANEL_LANGS = {
  fr: {
    dir:'ltr',
    'nav-dash':'Dashboard','nav-res':'Réservations','nav-vehicles':'Véhicules','nav-vidange':'Vidange',
    'nav-stats':'Statistiques','settings':'Paramètres','logout':'Déconnexion',
    'lg-title':'Réservations','lg-connexion':'Connexion','lg-desc':'Accès réservé aux administrateurs',
    'lg-user':'Identifiant','lg-user-ph':'Votre identifiant','lg-pass':'Mot de passe','lg-submit':'Se connecter →',
    'lg-forgot':'Mot de passe oublié ?','lg-recovery':'🔑 Récupération','lg-answer':'Votre réponse','lg-verify':'Vérifier →',
    'lg-newuser':'Nouvel identifiant','lg-newpass':'Nouveau mot de passe','lg-reset':'Réinitialiser →','lg-back':'← Retour',
    'topbar-admin':'👤 Admin',
    'dash-recent':'Dernières réservations','dash-seeall':'Voir tout →','dash-pending':'En attente','dash-status':'Répartition des statuts',
    'res-search-ph':'🔍 Rechercher nom, voiture, ville, tél...','res-all':'Tous les statuts',
    'res-add':'➕ Ajouter une réservation','res-export':'⬇️ Export Excel','res-clear':'🗑️ Vider','res-empty':'Aucune réservation. Cliquez sur "➕ Ajouter une réservation".',
    'th-client':'Client','th-vehicle':'Véhicule','th-city':'Lieu','th-dates':'Dates','th-duration':'Durée',
    'th-total':'Total','th-payment':'Paiement','th-status':'Statut','th-actions':'Actions',
    'st-pending':'En attente','st-payment_pending':'Paiement en cours','st-confirmed':'Confirmé','st-completed':'Terminé','st-cancelled':'Annulé',
    'veh-add':'➕ Ajouter un véhicule','veh-empty':'Aucun véhicule. Cliquez sur "➕ Ajouter un véhicule".',
    'veh-available':'Disponible','veh-reserved':'Réservé','veh-maintenance':'Chez le mécanicien','veh-accident':'Accidenté',
    'vid-empty':'Aucun véhicule. Ajoutez des véhicules dans la section Véhicules.',
    'stat-status':'📊 Statuts','stat-topcars':'🚗 Top véhicules','stat-topcities':'📍 Top destinations','stat-revenue':'💰 Revenus par réservation',
    'set-lang-t':'🌐 Langue du panneau','set-lang':'Langue',
    'set-agency-t':"🏢 Informations de l'agence",'set-logo':"Logo de l'agence",'set-logo-remove':'🗑️ Retirer le logo',
    'set-name':"Nom de l'agence",'set-phone':'Téléphone / WhatsApp','set-email':'Email','set-address':'Adresse','set-save':'💾 Enregistrer',
    'set-creds-t':'🔐 Identifiants de connexion','set-newuser':'Nouvel identifiant','set-newpass':'Nouveau mot de passe',
    'set-newpass-ph':'Laisser vide pour ne pas changer','set-creds-save':'🔑 Mettre à jour les identifiants',
    'set-secq-t':'❓ Question de sécurité (récupération mot de passe)','set-question':'Question','set-answer':'Réponse','set-secq-save':'💾 Enregistrer la question',
    'set-danger-t':'⚠️ Zone de danger','set-danger-s':"Réinitialise toutes les données de l'application (réservations, voitures, offres, paramètres).",
    'set-danger-btn':'🗑️ Réinitialisation complète',
    'exp-title':'📊 Export Excel','exp-desc':'Choisissez la période à exporter.','exp-week':'📅 Cette semaine','exp-month':'🗓️ Ce mois (30 jours)',
    'exp-3m':'📆 3 derniers mois','exp-6m':'📆 6 derniers mois','exp-year':'📅 Cette année (12 mois)','exp-all':'🗂️ Toutes les données',
    'exp-download':'⬇️ Télécharger Excel','exp-cancel':'Annuler',
    'f-name':'Nom du client','f-phone':'Téléphone','f-email':'Email','f-email-opt':'Email (optionnel)',
    'f-vehicle':'Véhicule','f-vehicle-choose':'— Choisir —','f-city':'Lieu de livraison','f-start':'Date départ','f-end':'Date retour',
    'f-total':'Total (MAD)','f-paytype':'Statut paiement','f-paid-full':'✅ Payé complet','f-paid-deposit':'💳 Avance','f-paid-none':'⏳ Rien payé',
    'f-paid-amount':'Montant déjà payé / avance (MAD)','f-paid-amount2':'Déjà payé (MAD)',
    'f-caution-check':'Caution / Garantie prise','f-caution-amount':'Montant de la caution (MAD)',
    'btn-save':'💾 Enregistrer','btn-cancel':'Annuler','btn-update':'💾 Mettre à jour',
    'm-manual-title':'📞 Nouvelle réservation manuelle','m-edit-title':'✏️ Modifier la réservation',
    'avail-ok':'✅ Disponible pour ces dates','avail-no-accident':'❌ Indisponible — véhicule accidenté','avail-no-maint':'❌ Indisponible — chez le mécanicien',
    'avail-no-overlap':'❌ Indisponible — déjà réservé du','avail-to':'au',
    'd-client':'👤 Client','d-phone':'📞 Téléphone','d-email':'✉️ Email','d-vehicle':'🚗 Véhicule','d-place':'📍 Lieu',
    'd-start':'📅 Départ','d-end':'📅 Retour','d-duration':'⏱ Durée','d-price-day':'💵 Prix/jour','d-total':'💰 Total à payer',
    'd-payment':'💳 Paiement','d-paid':'✅ Déjà payé','d-due':'⏳ Reste','d-caution':'🔒 Caution','d-caution-none':'Non prise',
    'd-created':'🕐 Créé le','btn-edit-all':'✏️ Modifier toute la réservation','btn-confirm':'✅ Confirmer','btn-reject':'❌ Annuler',
    'btn-wa':'📲 WhatsApp','btn-delete':'🗑️ Supprimer','btn-close':'Fermer','btn-invoice':'🧾 Télécharger la facture',
    'm-vehicle-add':'Ajouter un véhicule','m-vehicle-edit':'Modifier un véhicule','m-vehicle-name':'Nom du véhicule','m-vehicle-plate':'Plaque',
    'm-vehicle-status':'Statut','m-vehicle-note':'Note (accident / mécanique)','m-vehicle-photos':'Photos du véhicule',
    'm-cal-title':'📅 Calendrier','m-block-title':'⛔ Réserver','m-block-client':'Client (optionnel)','m-block-save':'💾 Bloquer ces dates',
    'm-cal-avail':'🟢 Disponible','m-cal-reserved':'🔴 Réservé','m-cal-today':"🟡 Aujourd'hui",
    'vf-name':'Nom du véhicule','vf-plate':'Plaque','vf-brand':'Marque','vf-model':'Modèle','vf-year':'Année',
    'vf-color':'Couleur','vf-fuel':'Carburant','vf-gearbox':'Boîte','vf-price':'Prix/jour (MAD)','vf-mileage':'Kilométrage actuel',
    'vf-lastvidange':'Dernière vidange (km)','vf-interval':'Intervalle vidange (km)','vf-insurance':'Assurance — échéance','vf-visit':'Visite technique — échéance',
    'vid-due':'Vidange dépassée','vid-soon':'Vidange proche (≤1000km)','vid-ok':'OK','vid-overdue':'Vidange dépassée de','vid-remaining':'km restants',
    'vid-last':'Dernière vidange','vid-interval':'Intervalle','vid-next':'Prochaine vidange','btn-edit':'Modifier',
    titles:{dashboard:'📋 Dashboard',reservations:'📋 Réservations',vehicles:'🚙 Véhicules',vidange:'🛢️ Vidange',stats:'📊 Statistiques',chats:'Conversations',settings:'⚙️ Paramètres'} },
  en: {
    dir:'ltr',
    'nav-dash':'Dashboard','nav-res':'Reservations','nav-vehicles':'Vehicles','nav-vidange':'Oil change',
    'nav-stats':'Statistics','settings':'Settings','logout':'Log out',
    'lg-title':'Reservations','lg-connexion':'Login','lg-desc':'Restricted to administrators',
    'lg-user':'Username','lg-user-ph':'Your username','lg-pass':'Password','lg-submit':'Sign in →',
    'lg-forgot':'Forgot password?','lg-recovery':'🔑 Recovery','lg-answer':'Your answer','lg-verify':'Verify →',
    'lg-newuser':'New username','lg-newpass':'New password','lg-reset':'Reset →','lg-back':'← Back',
    'topbar-admin':'👤 Admin',
    'dash-recent':'Latest reservations','dash-seeall':'See all →','dash-pending':'Pending','dash-status':'Status breakdown',
    'res-search-ph':'🔍 Search name, car, city, phone...','res-all':'All statuses',
    'res-add':'➕ Add a reservation','res-export':'⬇️ Export Excel','res-clear':'🗑️ Clear','res-empty':'No reservations. Click "➕ Add a reservation".',
    'th-client':'Client','th-vehicle':'Vehicle','th-city':'Location','th-dates':'Dates','th-duration':'Duration',
    'th-total':'Total','th-payment':'Payment','th-status':'Status','th-actions':'Actions',
    'st-pending':'Pending','st-payment_pending':'Payment in progress','st-confirmed':'Confirmed','st-completed':'Completed','st-cancelled':'Cancelled',
    'veh-add':'➕ Add a vehicle','veh-empty':'No vehicles. Click "➕ Add a vehicle".',
    'veh-available':'Available','veh-reserved':'Reserved','veh-maintenance':'At the mechanic','veh-accident':'In an accident',
    'vid-empty':'No vehicles. Add vehicles in the Vehicles section.',
    'stat-status':'📊 Statuses','stat-topcars':'🚗 Top vehicles','stat-topcities':'📍 Top destinations','stat-revenue':'💰 Revenue per reservation',
    'set-lang-t':'🌐 Panel language','set-lang':'Language',
    'set-agency-t':'🏢 Agency information','set-logo':'Agency logo','set-logo-remove':'🗑️ Remove logo',
    'set-name':'Agency name','set-phone':'Phone / WhatsApp','set-email':'Email','set-address':'Address','set-save':'💾 Save',
    'set-creds-t':'🔐 Login credentials','set-newuser':'New username','set-newpass':'New password',
    'set-newpass-ph':'Leave empty to keep current','set-creds-save':'🔑 Update credentials',
    'set-secq-t':'❓ Security question (password recovery)','set-question':'Question','set-answer':'Answer','set-secq-save':'💾 Save question',
    'set-danger-t':'⚠️ Danger zone','set-danger-s':'Resets all app data (reservations, cars, offers, settings).',
    'set-danger-btn':'🗑️ Full reset',
    'exp-title':'📊 Excel export','exp-desc':'Choose the period to export.','exp-week':'📅 This week','exp-month':'🗓️ This month (30 days)',
    'exp-3m':'📆 Last 3 months','exp-6m':'📆 Last 6 months','exp-year':'📅 This year (12 months)','exp-all':'🗂️ All data',
    'exp-download':'⬇️ Download Excel','exp-cancel':'Cancel',
    'f-name':'Client name','f-phone':'Phone','f-email':'Email','f-email-opt':'Email (optional)',
    'f-vehicle':'Vehicle','f-vehicle-choose':'— Choose —','f-city':'Delivery location','f-start':'Start date','f-end':'Return date',
    'f-total':'Total (MAD)','f-paytype':'Payment status','f-paid-full':'✅ Fully paid','f-paid-deposit':'💳 Deposit','f-paid-none':'⏳ Nothing paid',
    'f-paid-amount':'Amount already paid / deposit (MAD)','f-paid-amount2':'Already paid (MAD)',
    'f-caution-check':'Security deposit taken','f-caution-amount':'Deposit amount (MAD)',
    'btn-save':'💾 Save','btn-cancel':'Cancel','btn-update':'💾 Update',
    'm-manual-title':'📞 New manual reservation','m-edit-title':'✏️ Edit reservation',
    'avail-ok':'✅ Available for these dates','avail-no-accident':'❌ Unavailable — vehicle in an accident','avail-no-maint':'❌ Unavailable — at the mechanic',
    'avail-no-overlap':'❌ Unavailable — already booked from','avail-to':'to',
    'd-client':'👤 Client','d-phone':'📞 Phone','d-email':'✉️ Email','d-vehicle':'🚗 Vehicle','d-place':'📍 Location',
    'd-start':'📅 Departure','d-end':'📅 Return','d-duration':'⏱ Duration','d-price-day':'💵 Price/day','d-total':'💰 Total due',
    'd-payment':'💳 Payment','d-paid':'✅ Already paid','d-due':'⏳ Remaining','d-caution':'🔒 Deposit','d-caution-none':'Not taken',
    'd-created':'🕐 Created on','btn-edit-all':'✏️ Edit whole reservation','btn-confirm':'✅ Confirm','btn-reject':'❌ Cancel',
    'btn-wa':'📲 WhatsApp','btn-delete':'🗑️ Delete','btn-close':'Close','btn-invoice':'🧾 Download invoice',
    'm-vehicle-add':'Add a vehicle','m-vehicle-edit':'Edit vehicle','m-vehicle-name':'Vehicle name','m-vehicle-plate':'Plate',
    'm-vehicle-status':'Status','m-vehicle-note':'Note (accident / mechanic)','m-vehicle-photos':'Vehicle photos',
    'm-cal-title':'📅 Calendar','m-block-title':'⛔ Reserve','m-block-client':'Client (optional)','m-block-save':'💾 Block these dates',
    'm-cal-avail':'🟢 Available','m-cal-reserved':'🔴 Reserved','m-cal-today':'🟡 Today',
    'vf-name':'Vehicle name','vf-plate':'Plate','vf-brand':'Brand','vf-model':'Model','vf-year':'Year',
    'vf-color':'Color','vf-fuel':'Fuel','vf-gearbox':'Gearbox','vf-price':'Price/day (MAD)','vf-mileage':'Current mileage',
    'vf-lastvidange':'Last oil change (km)','vf-interval':'Oil change interval (km)','vf-insurance':'Insurance — due date','vf-visit':'Technical inspection — due date',
    'vid-due':'Oil change overdue','vid-soon':'Oil change soon (≤1000km)','vid-ok':'OK','vid-overdue':'Overdue by','vid-remaining':'km remaining',
    'vid-last':'Last oil change','vid-interval':'Interval','vid-next':'Next oil change','btn-edit':'Edit',
    titles:{dashboard:'📋 Dashboard',reservations:'📋 Reservations',vehicles:'🚙 Vehicles',vidange:'🛢️ Oil change',stats:'📊 Statistics',chats:'Conversations',settings:'⚙️ Settings'} },
  ar: {
    dir:'rtl',
    'nav-dash':'لوحة التحكم','nav-res':'الحجوزات','nav-vehicles':'السيارات','nav-vidange':'الفيدانج',
    'nav-stats':'الإحصائيات','settings':'الإعدادات','logout':'تسجيل الخروج',
    'lg-title':'الحجوزات','lg-connexion':'تسجيل الدخول','lg-desc':'الدخول مخصص للمسؤولين فقط',
    'lg-user':'اسم المستخدم','lg-user-ph':'اسم المستخدم ديالك','lg-pass':'كلمة السر','lg-submit':'← دخول',
    'lg-forgot':'نسيتي كلمة السر؟','lg-recovery':'🔑 استرجاع','lg-answer':'الجواب ديالك','lg-verify':'← تحقق',
    'lg-newuser':'اسم مستخدم جديد','lg-newpass':'كلمة سر جديدة','lg-reset':'← إعادة تعيين','lg-back':'رجوع →',
    'topbar-admin':'👤 المسؤول',
    'dash-recent':'آخر الحجوزات','dash-seeall':'← شوف الكل','dash-pending':'فالانتظار','dash-status':'توزيع الحالات',
    'res-search-ph':'🔍 بحث بالاسم، السيارة، المدينة، الهاتف...','res-all':'جميع الحالات',
    'res-add':'➕ إضافة حجز','res-export':'⬇️ تصدير Excel','res-clear':'🗑️ مسح','res-empty':'لا توجد حجوزات. اضغط على "➕ إضافة حجز".',
    'th-client':'الكليان','th-vehicle':'السيارة','th-city':'المكان','th-dates':'التواريخ','th-duration':'المدة',
    'th-total':'الإجمالي','th-payment':'الدفع','th-status':'الحالة','th-actions':'إجراءات',
    'st-pending':'فالانتظار','st-payment_pending':'الدفع جاري','st-confirmed':'مؤكد','st-completed':'منتهي','st-cancelled':'ملغى',
    'veh-add':'➕ إضافة سيارة','veh-empty':'لا توجد سيارات. اضغط على "➕ إضافة سيارة".',
    'veh-available':'متاحة','veh-reserved':'محجوزة','veh-maintenance':'عند المكانيك','veh-accident':'حادثة',
    'vid-empty':'لا توجد سيارات. زيد سيارات فقسم السيارات.',
    'stat-status':'📊 الحالات','stat-topcars':'🚗 أفضل السيارات','stat-topcities':'📍 أفضل الوجهات','stat-revenue':'💰 الإيرادات حسب الحجز',
    'set-lang-t':'🌐 لغة لوحة التحكم','set-lang':'اللغة',
    'set-agency-t':'🏢 معلومات الوكالة','set-logo':'شعار الوكالة','set-logo-remove':'🗑️ حذف الشعار',
    'set-name':'اسم الوكالة','set-phone':'الهاتف / واتساب','set-email':'البريد الإلكتروني','set-address':'العنوان','set-save':'💾 حفظ',
    'set-creds-t':'🔐 معلومات تسجيل الدخول','set-newuser':'اسم مستخدم جديد','set-newpass':'كلمة سر جديدة',
    'set-newpass-ph':'خليه خاوي إلا ماباغيش تبدلو','set-creds-save':'🔑 تحديث المعلومات',
    'set-secq-t':'❓ سؤال الأمان (استرجاع كلمة السر)','set-question':'السؤال','set-answer':'الجواب','set-secq-save':'💾 حفظ السؤال',
    'set-danger-t':'⚠️ منطقة الخطر','set-danger-s':'كيصيفط جميع بيانات التطبيق (الحجوزات، السيارات، العروض، الإعدادات).',
    'set-danger-btn':'🗑️ إعادة تعيين كاملة',
    'exp-title':'📊 تصدير Excel','exp-desc':'اختر الفترة للتصدير.','exp-week':'📅 هاد الأسبوع','exp-month':'🗓️ هاد الشهر (30 يوم)',
    'exp-3m':'📆 آخر 3 أشهر','exp-6m':'📆 آخر 6 أشهر','exp-year':'📅 هاد السنة (12 شهر)','exp-all':'🗂️ جميع البيانات',
    'exp-download':'⬇️ تحميل Excel','exp-cancel':'إلغاء',
    'f-name':'اسم الكليان','f-phone':'الهاتف','f-email':'البريد الإلكتروني','f-email-opt':'البريد الإلكتروني (اختياري)',
    'f-vehicle':'السيارة','f-vehicle-choose':'— اختر —','f-city':'مكان التوصيل','f-start':'تاريخ الذهاب','f-end':'تاريخ الرجوع',
    'f-total':'الإجمالي (MAD)','f-paytype':'حالة الدفع','f-paid-full':'✅ مدفوع بالكامل','f-paid-deposit':'💳 تقدمة','f-paid-none':'⏳ ماشي مدفوع',
    'f-paid-amount':'المبلغ المدفوع / التقدمة (MAD)','f-paid-amount2':'المدفوع (MAD)',
    'f-caution-check':'الضمان/الكوسيون مأخوذ','f-caution-amount':'مبلغ الضمان (MAD)',
    'btn-save':'💾 حفظ','btn-cancel':'إلغاء','btn-update':'💾 تحديث',
    'm-manual-title':'📞 حجز يدوي جديد','m-edit-title':'✏️ تعديل الحجز',
    'avail-ok':'✅ متاحة فهاد التواريخ','avail-no-accident':'❌ غير متاحة — السيارة حادثة','avail-no-maint':'❌ غير متاحة — عند المكانيك',
    'avail-no-overlap':'❌ غير متاحة — محجوزة من','avail-to':'إلى',
    'd-client':'👤 الكليان','d-phone':'📞 الهاتف','d-email':'✉️ البريد الإلكتروني','d-vehicle':'🚗 السيارة','d-place':'📍 المكان',
    'd-start':'📅 الذهاب','d-end':'📅 الرجوع','d-duration':'⏱ المدة','d-price-day':'💵 السعر/اليوم','d-total':'💰 الإجمالي للدفع',
    'd-payment':'💳 الدفع','d-paid':'✅ المدفوع','d-due':'⏳ الباقي','d-caution':'🔒 الضمان','d-caution-none':'ماخدمتش',
    'd-created':'🕐 تسجل فـ','btn-edit-all':'✏️ تعديل الحجز كامل','btn-confirm':'✅ تأكيد','btn-reject':'❌ إلغاء',
    'btn-wa':'📲 واتساب','btn-delete':'🗑️ حذف','btn-close':'إغلاق','btn-invoice':'🧾 تحميل الفاكتور',
    'm-vehicle-add':'إضافة سيارة','m-vehicle-edit':'تعديل سيارة','m-vehicle-name':'اسم السيارة','m-vehicle-plate':'الماتريكول',
    'm-vehicle-status':'الحالة','m-vehicle-note':'ملاحظة (أكسيدون / مكانيك)','m-vehicle-photos':'صور السيارة',
    'm-cal-title':'📅 الكلندري','m-block-title':'⛔ حجز','m-block-client':'الكليان (اختياري)','m-block-save':'💾 حجز هاد التواريخ',
    'm-cal-avail':'🟢 متاحة','m-cal-reserved':'🔴 محجوزة','m-cal-today':'🟡 اليوم',
    'vf-name':'اسم السيارة','vf-plate':'الماتريكول','vf-brand':'الماركة','vf-model':'الموديل','vf-year':'السنة',
    'vf-color':'الكولور','vf-fuel':'الكاربوران','vf-gearbox':'البواط','vf-price':'السعر/اليوم (MAD)','vf-mileage':'الكيلومتراج الحالي',
    'vf-lastvidange':'آخر فيدانج (km)','vf-interval':'إنترفال الفيدانج (km)','vf-insurance':'التأمين — تاريخ الانتهاء','vf-visit':'الزيارة التقنية — تاريخ الانتهاء',
    'vid-due':'الفيدانج فاتت','vid-soon':'الفيدانج قريبة (≤1000km)','vid-ok':'مزيان','vid-overdue':'فاتت بـ','vid-remaining':'كم باقي',
    'vid-last':'آخر فيدانج','vid-interval':'الإنترفال','vid-next':'الفيدانج الجاية','btn-edit':'تعديل',
    titles:{dashboard:'📋 لوحة التحكم',reservations:'📋 الحجوزات',vehicles:'🚙 السيارات',vidange:'🛢️ الفيدانج',stats:'📊 الإحصائيات',chats:'المحادثات',settings:'⚙️ الإعدادات'} },
};

function curLang() { return localStorage.getItem('md_panel_lang') || 'fr'; }
function T(key) { const L = PANEL_LANGS[curLang()] || PANEL_LANGS.fr; return L[key] != null ? L[key] : (PANEL_LANGS.fr[key] || key); }

function applyPanelLang(code) {
  const L = PANEL_LANGS[code] || PANEL_LANGS.fr;
  localStorage.setItem('md_panel_lang', code);
  document.documentElement.lang = code;
  document.documentElement.dir = L.dir;
  document.querySelectorAll('[data-pt]').forEach(el => {
    const v = L[el.dataset.pt];
    if (v) el.textContent = v;
  });
  document.querySelectorAll('[data-pt-ph]').forEach(el => {
    const v = L[el.dataset.ptPh];
    if (v) el.placeholder = v;
  });
  const sel = document.getElementById('panelLangSel');
  if (sel) sel.value = code;
  const pageTitle = document.getElementById('pageTitle');
  if (pageTitle && window.currentAdminTab) pageTitle.textContent = L.titles[window.currentAdminTab] || pageTitle.textContent;
  if (window.currentAdminTab && typeof showTab === 'function' && document.getElementById('app')?.style.display !== 'none') {
    const activeLink = document.querySelector('.sb-link.active');
    if (activeLink) showTab(window.currentAdminTab, activeLink);
  }
}

document.addEventListener('DOMContentLoaded', () => {
  applyPanelLang(localStorage.getItem('md_panel_lang') || 'fr');
});
